services:
  libcoap-proxy:
    build:
      context: ./coap2http-proxy
      dockerfile: Dockerfile
    image: my-coap2http-server
    container_name: my-coap2http-server
    network_mode: host
    stdin_open: true
    tty: true
    command: ["./build/coap2HttpServer", "-A", "::1", "-c", "./certs/server_cert.pem", "-j", "./certs/server_key.pem", "-P", ",my_proxy"]
    restart: "no"

  nginx-proxy:
    build:
      context: ./nginx_reverse_proxy/quantis-qrng-tls-pq-bench/quantis-qrng-nginx
      dockerfile: Dockerfile
    image: oqs-nginx
    container_name: oqs-nginx
    network_mode: host
    ports:
      - "4433:4433"
    restart: "no"

  qrng-api:
    build:
      context: ./eaas-quantis-qrng-api
      dockerfile: Dockerfile
      args:
        OS_XOR: ${QRNG_BUILD_OS_XOR:-ON}
    image: qrng-api
    container_name: qrng-api
    network_mode: host
    devices:
      - ${QRNG_DOCKER_DEVICE:-/dev/qrandom0:/dev/qrandom0:r}
    ports:
      - "6065:6065"
    command:
      - --source
      - ${QRNG_SOURCE:-pcie}
      - --pcie-output
      - ${QRNG_PCIE_OUTPUT:-extracted}
      - --device-number
      - ${QRNG_DEVICE_NUMBER:-0}
      - --qrandom
      - ${QRNG_DEVICE_PATH:-/dev/qrandom0}
      - --extract
      - ${QRNG_EXTRACT:-off}
      - --matrix
      - ${QRNG_MATRIX:-/opt/quantis/share/quantis/default_idq_matrix.dat}
      - --xor-os
      - ${QRNG_XOR_OS:-off}
      - --fallback
      - ${QRNG_FALLBACK:-on}
    restart: "no"
